name: Check Formatting

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-24.04
    steps:
      - name: format
        uses: docker://restyled/restyler-luaformatter:v1.3.6
        with:
          args: cd /github/workspace && ls -al
      - name: check-formatting
        run: |
          git diff
          git diff-index --quiet HEAD
