name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.4

      - uses: leafo/gh-actions-luarocks@v4.1.0

      - name: build
        run: |
          luarocks install busted

      - name: test
        run: |
          bin/test-all
